version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  open-pull-requests-limit: 10
  schedule:
    interval: weekly
  commit-message:
    prefix: "fix"
    prefix-development: "chore"
    include: "scope"
