name: Deploy to github
on:
  push:
    branches:
      - master
      - 'next**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Checkout foreman-js
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install foreman-js npm dependencies
        run: npm install
      - name: Publish to github
        run: ./scripts/publish-github-ci.sh
