name: Deploy to github
on:
  push:
    branches:
      - master
      - 'next**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Checkout foreman-js
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install foreman-js npm dependencies
        run: npm install
      - name: Configure foreman-js-bot user
        env:
          GH_EMAIL: foreman-js-bot@theforeman.org
          GH_NAME: foreman-js-bot
        run: ./scripts/set-git-user-to-foreman-js-bot-ci.sh
      - name: Publish to github
        run: ./scripts/publish-github-ci.sh
