name: Deploy to npm
on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Checkout foreman-js
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install foreman-js npm dependencies
        run: npm install
      - name: Build foreman-js
        run: npm run build
      - name: Prepare publish no npm
        run: ./scripts/prepare-publish-npm-ci.sh
      - name: Publish to npm
        run: ./scripts/publish-npm-ci.sh
      - name: Comment on the pull-request about the new release
        run: ./scripts/post-publish-comment-github.sh
